options:
  stat-interval:
    type: int
    default: 60
    description: |
      Interval (in seconds) at which the agent cron will run.
  backend-url:
    type: string
    default:
    description: |
      The cluster-api backend url.
  package-url:
    type: string
    default: private-212021838531.d.codeartifact.us-west-2.amazonaws.com/pypi/agents/simple/
    description: |
      Cluster agent package url without protocol, e.g. <some awesome domain>-<aws account id>.d.codeartifact.us-west-2.amazonaws.com/pypi/agents/simple/
  aws-access-key-id:
    type: string
    default:
    description: |
      AWS access key ID in plain text.
  aws-secret-access-key:
    type: string
    default:
    description: |
      AWS secret access key in plain text.
  aws-region:
    type: string
    default: us-west-2
    description: |
      AWS region to which install the Cluster agent package
  auth0-domain:
    type: string
    default: omnivector.us.auth0.com
    description: |
      OIDC provider domain
  auth0-audience:
    type: string
    default: https://armada.omnivector.solutions
    description: |
      OIDC provider audience
  auth0-client-id:
    type: string
    default:
    description: |
      Client ID used to issue JWTs
  auth0-client-secret:
    type: string
    default:
    description: |
      Secret to protect OIDC client resources

