options:
  api-key:
    type: string
    default:
    description: |
      The backend api-key
  base-api-url:
    type: string
    default:
    description: |
      The armada-api backend url
  pypi-url:
    type: string
    default:
    description: |
      Base pypi url, e.g. https://mypypi.example.com
  pypi-username:
    type: string
    default:
    description: |
      PYPI USERNAME
  pypi-password:
    type: string
    default:
    description: |
      PYPI password in plain text.
