options:

  # Used by systemd to specify the frequency of the agent execution
  stat-interval:
    type: int
    default: 60
    description: |
      Interval (in seconds) at which the agent process will run.

  # Resource URLs
  base-api-url:
    type: string
    default:
    description: |
      The cluster-api url.
  base-slurmrestd-url:
    type: string
    default: http://127.0.0.1:6820
    description: |
      The url for the Slurm REST API.

  # Auth related settings
  oidc-domain:
    type: string
    default:
    description: |
      OIDC provider domain
  oidc-audience:
    type: string
    default:
    description: |
      OIDC provider audience
  oidc-client-id:
    type: string
    default:
    description: |
      Client ID used to issue JWTs
  oidc-client-secret:
    type: string
    default:
    description: |
      Secret to protect OIDC client resources
  slurm-user-mapper:
    type: string
    default: LDAP
    description: |
      Type of user-mapper to use. May be LDAP or SINGLE_USER
  ldap-domain:
    type: string
    description: |
      Domain for the LDAP host used for user identity on the server
  ldap-username:
    type: string
    description: |
      The username of the user that has directory-wide read permissions (or admin)
  ldap-password:
    type: string
    description: |
      The password for the user that has directory-wide read permissions (or admin)
  ldap-auth-type:
    type: string
    default: NTLM
    description: |
      The type of auth to use for ldap connection. (Should usually be NTLM)

  # Other settings
  cache-dir:
    type: string
    default: /var/cache/cluster-agent
    description: |
      The directory where the cluster-agent may cache runtime values
  sentry-dsn:
    type: string
    default:
    description: |
      The client url for sending error events to sentry
  x-slurm-user-name:
    type: string
    default: slurm
    description: |
      The default username to use for requests to the Slurm REST API
