options:
  api-key:
    type: string
    default:
    description: |
      The backend api-key.
  backend-url:
    type: string
    default:
    description: |
      The armada-api backend url.
  package-url:
    type: string
    default: private-212021838531.d.codeartifact.us-west-2.amazonaws.com/pypi/armada-agent/simple/
    description: |
      Armada agent package url without protocol, e.g. <some aewsome domain>-<aws account id>.d.codeartifact.us-west-2.amazonaws.com/pypi/armada-agent/simple/
  aws-access-key-id:
    type: string
    default:
    description: |
      AWS access key ID in plain text.
  aws-secret-access-key:
    type: string
    default:
    description: |
      AWS secret access key in plain text.
  aws-region:
    type: string
    default: us-west-2
    description: |
      AWS region to which install the Armada agent package
