options:
  api-key:
    type: string
    default:
    description: |
      The backend api-key
  base-api-url:
    type: string
    default:
    description: |
      The armada-api backend url
  pypi-url:
    type: string
    default:
    description: |
      Full PYPI URL (with HTTPS protocol) e.g. https://pypi.org/simple
  pypi-username:
    type: string
    default:
    description: |
      PYPI USERNAME
  pypi-password:
    type: string
    default:
    description: |
      PYPI PASSWORD
