options:
  jwt:
    type: string
    default:
    description: |
      The slurmrestd jwt key
  api-key:
    type: string
    default:
    description: |
      The backend api-key
  backend-url:
    type: string
    default:
    description: |
      The armada-api backend url
  pypi-url:
    type: string
    default:
    description: |
      PYPI URL
  pypi-username:
    type: string
    default:
    description: |
      PYPI USERNAME
  pypi-password:
    type: string
    default:
    description: |
      PYPI PASSWORD
 
